CREATE TABLE rates(
    id SERIAL PRIMARY KEY,
    address_line1 VARCHAR NOT NULL,
    address_line2 VARCHAR,
    city VARCHAR NOT NULL,
    state VARCHAR,
    zip INTEGER NOT NULL,
    country VARCHAR NOT NULL, 
    height DECIMAL NOT NULL,
    length DECIMAL NOT NULL,
    width DECIMAL NOT NULL,
    weight DECIMAL NOT NULL,
    CALI_CARRIER VARCHAR NOT NULL,
    CALI_SERVICE VARCHAR NOT NULL,
    CALI_POSTAGE_FEE MONEY NOT NULL,
    OHIO_CARRIER VARCHAR NOT NULL,
    OHIO_SERVICE VARCHAR NOT NULL,
    OHIO_POSTAGE_FEE MONEY NOT NULL
)